### CADASTRO DE USUÁRIO MASTER

POST http://localhost:3333/api/users/register
Content-Type: application/json

{
  "name": "Iago",
  "email": "vsiago24@gmail.com",
  "password": "81510156",
  "role": "Master"
}

### FAZER LOGIN DO USUÁRIO MASTER

POST http://localhost:3333/api/users/login
Content-Type: application/json

{
  "data": "vsiago23@gmail.com",
  "password": "81510156"
}

### CADASTRO DE USUÁRIO COMUM

POST http://localhost:3333/api/users/register
Content-Type: application/json

{
  "name": "Maria",
  "email": "maria@gmail.com",
  "password": "132456"
}

### FAZER LOGIN DO USUÁRIO COMUM

POST http://localhost:3333/api/users/login
Content-Type: application/json

{
  "data": "maria@gmail.com",
  "password": "132456"
}

### Login via LDAP

POST http://localhost:3333/api/users/login
Content-Type: application/json

{
  "data": "iago.vieira",
  "password": "Ai17003131!"
}


### Login via LDAP


POST http://localhost:3333/api/users/login
Content-Type: application/json

{
  "data": "wallace.moreira",
  "password": "Aleijado1234"
}

### Login via LDAP

POST http://localhost:3333/api/users/login
Content-Type: application/json

{
  "data": "ronyson.fonseca",
  "password": "Th&sims123"
}

############## A P P S #################

### Cadastrar App para o Membro
POST http://localhost:3333/api/apps/
Content-Type: application/json

{
  "apps": [
    {
      "name": "IPTU",
      "description": "Aplicativo IPTU.",
      "logo": "https://example.com/logos/oportunidades.png",
      "url": "https://example.com/oportunidades",
      "status": "ativo"
    }
  ]
}

### Cadastrar App para o tecnico
POST http://localhost:3333/api/apps/
Content-Type: application/json

{
  "apps": [
    {
      "name": "ChamadosTecnicos",
      "description": "Aplicativo ChamadosTecnicos.",
      "logo": "https://example.com/logos/oportunidades.png",
      "url": "https://example.com/oportunidades",
      "status": "ativo"
    }
  ]
}

### Cadastrar um App
POST http://localhost:3333/api/apps/
Content-Type: application/json

{
  "apps": [
    {
      "name": "Agro Boi",
      "description": "Um aplicativo Agro Boi.",
      "logo": "https://example.com/logos/oportunidades.png",
      "url": "https://example.com/oportunidades",
      "status": "ativo"
    }
  ]
}


############## D E F I N I R  A P P S  P A R A  U S U Á R I O S #################

### Definir aplicativos para um usuário do LDAP manualmente
POST http://localhost:3333/api/users/definir-apps
Content-Type: application/json

{
  "username": "iago.vieira",
  "apps": ["Agro Boi"]
}

### Remover um app atribuido para um perfil LDAP
POST http://localhost:3333/api/users/remover-app
Content-Type: application/json

{
  "username": "iago.vieira",
  "apps": ["Agro Boi"]
}


### Definir aplicativos para um usuário do LDAP (tecnico)
POST http://localhost:3333/api/users/definir-apps
Content-Type: application/json

{
  "username": "iago.vieira",
  "apps": ["ChamadosTecnicos"]
}


### Buscar informações de um usuário
GET http://localhost:3333/api/users/iago.vieira
Content-Type: application/json

### Buscar todos os usuários
GET http://localhost:3333/api/users
Content-Type: application/json

###

# Teste de autenticação do usuário (/me)
GET http://localhost:3333/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YWEzMWQ4ZDM0OThmNTFjYzc5NWIzYiIsIm5hbWUiOiJJYWdvIiwiZW1haWwiOiJpYWdvLnZpZWlyYUBpdGFndWFpLnJqLmdvdi5iciIsInJvbGUiOiJtZW1iZXIiLCJpYXQiOjE3MzkzODA3MDYsImV4cCI6MTczOTk4NTUwNn0.vDwfGmjogaiMq2F72zaPGCQCwNg8bYglfkZNvv_6C6I
Content-Type: application/json