### CADASTRO DE USUÁRIO MASTER

POST http://localhost:3333/api/users/register
Content-Type: application/json

{
  "name": "Iago",
  "email": "vsiago24@gmail.com",
  "password": "81510156",
  "role": "master"
}

### FAZER LOGIN DO USUÁRIO MASTER

POST http://localhost:3333/api/users/login
Content-Type: application/json

{
  "email": "vsiago23@gmail.com",
  "password": "81510156"
}

### CADASTRO DE USUÁRIO COMUM

POST http://localhost:3333/api/users/register
Content-Type: application/json

{
  "name": "Maria",
  "email": "maria@gmail.com",
  "password": "132456"
}

### FAZER LOGIN DO USUÁRIO COMUM

POST http://localhost:3333/api/users/login
Content-Type: application/json

{
  "data": "maria@gmail.com",
  "password": "132456"
}

### FAZER LOGIN COM USUÁRIO MASTER

POST http://localhost:3333/api/users/login
Content-Type: application/json

{
  "data": "vsiago23@gmail.com",
  "password": "81510156"
}

### Login via LDAP

POST http://localhost:3333/api/users/login
Content-Type: application/json

{
  "data": "iago.vieira",
  "password": "Ai17003131!"
}

### Cadastrar App por tipo de usuário

POST http://localhost:3333/api/apps/
Content-Type: application/json

{
  "apps": [
    {
      "name": "IPTU",
      "description": "Aplicativo IPTU.",
      "logo": "https://example.com/logos/oportunidades.png",
      "url": "https://example.com/oportunidades",
      "status": "ativo"
    }
  ]
}


### Login via LDAP

POST http://localhost:3333/api/users/login
Content-Type: application/json

{
  "data": "wallace.moreira",
  "password": "Aleijado1234"
}

### Login via LDAP

POST http://localhost:3333/api/users/login
Content-Type: application/json

{
  "data": "ronyson.fonseca",
  "password": "Th&sims123"
}
