### CADASTRO DE USUÁRIO MASTER

POST http://localhost:3333/api/users/register
Content-Type: application/json

{
  "name": "Iago",
  "email": "vsiago24@gmail.com",
  "password": "81510156",
  "role": "Master"
}

### FAZER LOGIN DO USUÁRIO MASTER

POST http://localhost:3333/api/users/login
Content-Type: application/json

{
  "data": "vsiago23@gmail.com",
  "password": "81510156"
}

### CADASTRO DE USUÁRIO COMUM

POST http://localhost:3333/api/users/register
Content-Type: application/json

{
  "name": "Maria",
  "email": "maria@gmail.com",
  "password": "132456"
}

### FAZER LOGIN DO USUÁRIO COMUM

POST http://localhost:3333/api/users/login
Content-Type: application/json

{
  "data": "maria@gmail.com",
  "password": "132456"
}

### Login via LDAP

POST http://localhost:3333/api/users/login
Content-Type: application/json

{
  "data": "iago.vieira",
  "password": "Ai17003131!"
}


### Login via LDAP


POST http://localhost:3333/api/users/login
Content-Type: application/json

{
  "data": "wallace.moreira",
  "password": "Aleijado1234"
}

### Login via LDAP

POST http://localhost:3333/api/users/login
Content-Type: application/json

{
  "data": "ronyson.fonseca",
  "password": "Th&sims123"
}

############## A P P S #################

### Cadastrar App para o Servidor
POST http://localhost:3333/api/apps/
Content-Type: application/json

{
  "apps": [
    {
      "name": "Biométrico Saúde",
      "description": "Um aplicativo de Biometria para funcionários da Saúde.",
      "logo": "https://example.com/logos/oportunidades.png",
      "url": "prefeitura@itaguai.rj.gov.br/biometrico-saude",
      "status": "ativo"
    }
  ]
}

### Cadastrar App para o tecnico
POST http://localhost:3333/api/apps/
Content-Type: application/json

{
  "apps": [
    {
      "name": "ChamadosTecnicos",
      "description": "Aplicativo ChamadosTecnicos.",
      "logo": "https://example.com/logos/oportunidades.png",
      "url": "https://example.com/oportunidades",
      "status": "ativo"
    }
  ]
}

### Cadastrar um App
POST http://localhost:3333/api/apps/
Content-Type: application/json

{
  "apps": [
    {
      "name": "BIC",
      "description": "Um aplicativo De Reurbanização.",
      "logo": "https://example.com/logos/oportunidades.png",
      "url": "https://example.com/oportunidades",
      "status": "ativo"
    }
  ]
}


############## D E F I N I R  A P P S  P A R A  U S U Á R I O S #################

### Definir aplicativos para um usuário do LDAP manualmente
POST http://localhost:3333/api/users/definir-apps
Content-Type: application/json

{
  "username": "ronyson.fonseca",
  "apps": ["BIC"]
}

### Remover um app atribuido para um perfil LDAP
POST http://localhost:3333/api/users/remover-app
Content-Type: application/json

{
  "username": "wallace.moreira",
  "apps": ["Agro Boi"]
}


### Definir aplicativos para um usuário do LDAP (tecnico)
POST http://localhost:3333/api/users/definir-apps
Content-Type: application/json

{
  "username": "iago.vieira",
  "apps": ["BIC"]
}


### Buscar informações de um usuário
GET http://localhost:3333/api/users/iago.vieira
Content-Type: application/json

### Buscar todos os usuários
GET http://localhost:3333/api/users
Content-Type: application/json

###

# Teste de autenticação do usuário (/me)
GET http://localhost:3333/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YWY5YmUwNTE2NTdlNzFlYTI5Nzg4NiIsIm5hbWUiOiJJYWdvIFNvdXphIFZpZWlyYSIsImVtYWlsIjoiaWFnby52aWVpcmFAaXRhZ3VhaS5yai5nb3YuYnIiLCJyb2xlIjoiU2Vydmlkb3IiLCJpYXQiOjE3Mzk5MDE4NzUsImV4cCI6MTc0MDUwNjY3NX0.kfj_0SAIPVTaxtL0ZWvCp3wSGy5VdB4rayCr19PIgKg
Content-Type: application/json

###

GET http://localhost:3333/api/ldap/users
Content-Type: application/json

###

POST http://localhost:3333/api/ldap/register-ldap-user
Content-Type: application/json

{
  "username": "iago.vieira"
}


### ********** Cadastrar ou Atualizar Apps ********** ###

POST http://localhost:3333/api/apps/
Content-Type: application/json

{
  "apps": [
    {
      "name": "BIC",
      "description": "Regularização fundiária de Itaguaí",
      "logoUrl": "/logo-bic.svg",
      "pathApp": "bic",
      "url": "https://bic.itaguai.rj.gov.br",
      "requiresAuth": true,
      "loginMethod": "email-password",
      "state": "ativo",
      "category": "Servidor",
      "allowedDepartments": ["Fazenda"]
    },
    {
      "name": "ItaMail",
      "description": "Aplicativo de E-mail do Servidor",
      "logoUrl": "/logo-itamail.svg",
      "pathApp": "itamail",
      "url": "https://itamail.itaguai.rj.gov.br",
      "requiresAuth": true,
      "loginMethod": "email-password",
      "state": "ativo",
      "category": "Servidor",
      "allowedDepartments": ["Fazenda"]
    },
    {
      "name": "Itadesk",
      "description": "Itadesk",
      "logoUrl": "/logo-itadesk.svg",
      "pathApp": "itadesk",
      "url": "https://itadesk.itaguai.rj.gov.br/",
      "requiresAuth": false,
      "state": "ativo",
      "category": "Servidor",
      "allowedDepartments": ["Area tecnica"]
    },
    {
      "name": "Protocolo",
      "description": "Aplicativo de protocolo do Servidor",
      "logoUrl": "/logo-protocolo.svg",
      "pathApp": "protocolo",
      "url": "https://adm.itaguai.rj.gov.br/adm/open.do?action=open&sys=PRO",
      "requiresAuth": true,
      "loginMethod": "email-password",
      "state": "ativo",
      "category": "Servidor",
      "allowedDepartments": ["Administração"]
    },
    {
      "name": "Licitação",
      "description": "Aplicativo de licitação do Servidor",
      "logoUrl": "/logo-licitacao.svg",
      "pathApp": "licitacao",
      "url": "https://adm.itaguai.rj.gov.br/adm/open.do?action=open&sys=LIC",
      "requiresAuth": true,
      "loginMethod": "email-password",
      "state": "ativo",
      "category": "Servidor",
      "allowedDepartments": ["Licitação"]
    },
    {
      "name": "Patrimônio",
      "description": "Aplicativo de patrimônio do Servidor",
      "logoUrl": "/logo-patrimonio.svg",
      "pathApp": "patrimonio",
      "url": "https://adm.itaguai.rj.gov.br/adm/open.do?action=open&sys=PAT",
      "requiresAuth": true,
      "loginMethod": "email-password",
      "state": "ativo",
      "category": "Servidor",
      "allowedDepartments": ["Patrimônio"]
    },
    {
      "name": "Almoxarifado",
      "description": "Aplicativo de almoxarifado do Servidor",
      "logoUrl": "/logo-almoxarifado.svg",
      "pathApp": "almoxarifado",
      "url": "https://adm.itaguai.rj.gov.br/adm/open.do?action=open&sys=ALM",
      "requiresAuth": true,
      "loginMethod": "email-password",
      "state": "ativo",
      "category": "Servidor",
      "allowedDepartments": ["Almoxarifado"]
    },
    {
      "name": "Jornal Oficial",
      "description": "Diário oficial do município",
      "logoUrl": "/logo-jornal-oficial.svg",
      "pathApp": "jornal-oficial",
      "url": "https://novoportal.itaguai.rj.gov.br/paginas/jornal-oficial",
      "requiresAuth": false,
      "category": "Cidadão",
      "state": "ativo"
    },
    {
      "name": "Transparência",
      "description": "Portal transparência do município",
      "logoUrl": "/logo-transparencia.svg",
      "pathApp": "transparencia",
      "url": "https://portal.transparencia.itaguai.rj.gov.br/",
      "requiresAuth": false,
      "category": "Cidadão",
      "state": "ativo"
    },
    {
      "name": "ISS",
      "description": "NFS-e",
      "logoUrl": "/logo-nfse.svg",
      "pathApp": "nfse",
      "url": "https://spe.itaguai.rj.gov.br/senhaweb/login.aspx",
      "requiresAuth": false,
      "category": "Cidadão",
      "state": "ativo"
    },
    {
      "name": "Emissão da 2ª via de IPTU",
      "description": "IPTU",
      "logoUrl": "/logo-iptu.svg",
      "pathApp": "iptu",
      "url": "https://siarm.itaguai.rj.gov.br/siarm/informacoes/2",
      "requiresAuth": false,
      "category": "Cidadão",
      "state": "ativo"
    }
  ]
}

### Buscar usuários por solução
GET http://localhost:3333/api/ldap/users/department/SMCTIC

### Buscar usuários por solução
GET http://localhost:3333/api/ldap/users/solution/SMFPL

### Buscar usuários por groups
GET http://localhost:3333/api/ldap/users/groups/ronyson.fonseca

### Buscar usuários por grupos
GET http://localhost:3333/api/ldap/users/groups/luiz.monteiro
